[features]
seeds = false
skip-lint = false

[programs.localnet]
agrotm = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/agrotm",
    "programs/agrotm-staking",
    "programs/agrotm-nft"
]

[test]
startup_wait = 10000
shutdown_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[test.genesis]
[test.genesis.agrotm]
address = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
program = "target/deploy/agrotm.so"

[test.genesis.agrotm-staking]
address = "Staking111111111111111111111111111111111111111111111"
program = "target/deploy/agrotm_staking.so"

[test.genesis.agrotm-nft]
address = "NFT111111111111111111111111111111111111111111111111"
program = "target/deploy/agrotm_nft.so" 