[phases.setup]
nixPkgs = ["python3", "make", "gcc"]

[phases.install]
cmds = ["chmod +x build-railway.sh", "npm ci --only=production --python=/usr/bin/python3"]

[phases.build]
cmds = ["./build-railway.sh"]

[start]
cmd = "npm start" 