name = "agroisync-public-api"
main = "src/public-api-worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "agroisync-db"
database_id = "a3eb1069-9c36-4689-9ee9-971245cb2d12"

[vars]
NODE_ENV = "production"
API_VERSION = "v1"

routes = [
  "agroisync.com/public/*"
]
