name: Notify Slack on Build/Deploy

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["CI/CD", "dependency-audit"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":rocket: Novo build/deploy realizado no AGROTM!\nBranch: ${{ github.ref }}\nStatus: ${{ github.event.workflow_run.conclusion }}\nAutor: ${{ github.actor }}\nVeja detalhes em: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
